
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org2
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  h2:
    console:
      enabled: true
  jackson:
#    default-property-inclusion: non_null
server:
  port: 8089